usb_cam:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 30.0
    pixel_format: "yuyv"
    image_width: 640
    image_height: 480
    camera_name: "pinky_camera"
    camera_info_url: "file:///home/pinky/camera_calibration.yaml"