[supervisord]
nodaemon=false
logfile=/home/team1-ai/roscamp-repo-1/services/ai_server/supervisor/supervisord.log

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:ai-server]
command=/home/team1-ai/ai_venv/bin/python3 /home/team1-ai/roscamp-repo-1/services/ai_server/moosinsa_ai_server.py
directory=/home/team1-ai/roscamp-repo-1/services/ai_server
autostart=true
autorestart=true
startretries=5
stdout_logfile=/home/team1-ai/roscamp-repo-1/services/ai_server/supervisor/ai-server.log
stderr_logfile=/home/team1-ai/roscamp-repo-1/services/ai_server/supervisor/ai-server-error.log
environment=PYTHONUNBUFFERED="1"
